### ISSUE TITLE
User level

### ISSUE THREAD

**Issue by ghuysmans** [qcarpentier/arsg-bot#15]
You could compute the users' level using a MySQL view, so that you wouldn't need to UPDATE the table. This would fix a race condition [there](https://github.com/qcarpentier/arsg-bot/blob/dd92cf8f667e2eaa18458ee854ac0be576e0ac00/index.js#L169). You might as well update that field at the same time, but there's still no need to actually store it (IMHO).

**Comment by ghuysmans** [comment]
[Your computation](https://github.com/qcarpentier/arsg-bot/blob/dd92cf8f667e2eaa18458ee854ac0be576e0ac00/index.js#L167) looks quite convoluted: why not `Math.floor(rows[0].message) + 1`?

**Comment by qcarpentier** [comment]
Hey @ghuysmans,
I fixed the computation of the leveling experience [here](https://github.com/qcarpentier/arsg-bot/blob/5509a72247c52f07b68a9732172f3af274da93b2/index.js#L147). Quite simple actually, but now, the levels look like [this](https://github.com/qcarpentier/arsg-bot/blob/5509a72247c52f07b68a9732172f3af274da93b2/index.js#L10).

I used a linearly rising level gap for calculating how much XP you should get to level up:

Level | XP | Difference
-- | -- | --
1 | 0 | -
2 | 1000 | 1000
3 | 3000 | 2000
4 | 6000 | 3000
5 | 10000 | 4000
6 | 15000 | 5000
7 | 21000 | 6000
8 | 28000 | 7000
9 | 36000 | 8000
10 | 45000 | 9000
