### ISSUE TITLE
MySQL connection pooling

### ISSUE THREAD

**Issue by ghuysmans** [qcarpentier/arsg-bot#16]
You could reuse some fixed number of MySQL connections instead of opening a new one each time you receive a message, this avoids putting too much pressure on your server and will make your bot a bit faster.

**Comment by qcarpentier** [comment]
Hey @ghuysmans,

I reworked the entire project to use MongoDb and Mongoose. :)

**Comment by ghuysmans** [comment]
Hi,
Why not! As long as your database is not too large and there aren't many clients, you're free to choose pretty much anything ;)
